export const searchCategories = [
  {
    category: "Health",
    filterItems: [
      { label: "health", name: "dairy-free" },
      { label: "health", name: "egg-free" },
      { label: "health", name: "fish-free" },
      { label: "health", name: "gluten-free" },
      {
        label: "health",
        name: "immuno-supportive",
      },
      { label: "health", name: "keto-friendly" },
      { label: "health", name: "kidney-friendly" },
      { label: "health", name: "kosher" },
      { label: "health", name: "low-sugar" },
      { label: "health", name: "Mediterranean" },
      { label: "health", name: "paleo" },
      { label: "health", name: "peanut-free" },
      { label: "health", name: "pork-free" },
      { label: "health", name: "red-meat-free" },
      { label: "health", name: "shellfish-free" },
      { label: "health", name: "soy-free" },
      { label: "health", name: "pescatarian" },
      { label: "health", name: "mediterranean" },
      { label: "health", name: "vegan" },
      { label: "health", name: "vegetarian" },
    ],
  },
  {
    category: "Cuisine",
    filterItems: [
      { label: "cuisineType", name: "American" },
      { label: "cuisineType", name: "Asian" },
      { label: "cuisineType", name: "British" },
      { label: "cuisineType", name: "Caribbean" },
      { label: "cuisineType", name: "Central Europe" },
      { label: "cuisineType", name: "Chinese" },
      { label: "cuisineType", name: "Eastern Europe" },
      { label: "cuisineType", name: "French" },
      { label: "cuisineType", name: "Indian" },
      { label: "cuisineType", name: "Italian" },
      { label: "cuisineType", name: "Japanese" },
      { label: "cuisineType", name: "Kosher" },
      { label: "cuisineType", name: "Mediterranean" },
      { label: "cuisineType", name: "Mexican" },
      { label: "cuisineType", name: "Middle Eastern" },
      { label: "cuisineType", name: "Nordic" },
      { label: "cuisineType", name: "South American" },
      { label: "cuisineType", name: "South East Asian" },
    ],
  },
  {
    category: "Dish",
    filterItems: [
      { label: "dishType", name: "Buscuits and cookies" },
      { label: "dishType", name: "Bread" },
      { label: "dishType", name: "Cereals" },
      { label: "dishType", name: "Condiments and sauces" },
      { label: "dishType", name: "Desserts" },
      { label: "dishType", name: "Drinks" },
      { label: "dishType", name: "Main Course" },
      { label: "dishType", name: "Pancake" },
      { label: "dishType", name: "Preps" },
      { label: "dishType", name: "Preserve" },
      { label: "dishType", name: "Salad" },
      { label: "dishType", name: "Sandwhiches" },
      { label: "dishType", name: "Side dish" },
      { label: "dishType", name: "Soup" },
      { label: "dishType", name: "Starter" },
      { label: "dishType", name: "Sweets" },
    ],
  },
  {
    category: "Diet",
    filterItems: [
      {
        label: "diet",
        name: "balanced",
      },
      {
        label: "diet",
        name: "high-fiber",
      },
      {
        label: "diet",
        name: "high-protein",
      },
      {
        label: "diet",
        name: "low-fat",
      },
      {
        label: "diet",
        name: "low-carb",
      },
      {
        label: "diet",
        name: "low-sodium",
      },
    ],
  },

  {
    category: "Meal",
    filterItems: [
      { label: "mealType", name: "breakfast" },
      { label: "mealType", name: "brunch" },
      {
        label: "meal-Type",
        name: "lunch/dinner",
      },
      { label: "mealType", name: "snack" },
    ],
  },
];
